apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blue-green-virtual-service
spec:
  hosts:
    - "*"
  gateways:
    - blue-green-gateway
  http:
    - route:
        - destination:
            host: blue-green-app
            subset: v1
          weight: 0
        - destination:
            host: blue-green-app
            subset: v2
          weight: 100