apiVersion: v1
kind: Secret
metadata:
  name: deploy-secret
  annotations:
    tekton.dev/docker-0: https://docker.io
type: kubernetes.io/basic-auth
stringData:
  username: <username>
  password: <password>
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dockerhub-account
secrets:
  - name: deploy-secret
