apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-task
spec:
  workspaces:
    - name: working-dir
  params:
    - name: DEPLOY_DIR
      type: string
    - name: VERSION
      type: string
  steps:
    - name: deploy-app
      image: quay.io/openshift/origin-cli:4.6
      workingDir: $(workspaces.working-dir.path)
      script: |
        #!/usr/bin/env bash
        cat <<EOF >$(params.DEPLOY_DIR)/kustomization.yaml
        nameSuffix: -$(params.VERSION)
        commonLabels:
          version: $(params.VERSION)
        resources:
        - deployment.yaml
        images:
        - name: deltael/blue-green-app
          newTag: $(params.VERSION)
        EOF

        kubectl apply -k $(params.DEPLOY_DIR)

        # This forces kubernetes pull the image even though the tag didn't change
        kubectl rollout restart deployment/blue-green-app-$(params.VERSION)
 