apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: istio-canary
spec:
  workspaces:
    - name: istio-manifest-dir
  params:
    - name: VIRTUAL_SERVICE_NAME
      type: string
      default: ""
    - name: APP_NAME
      type: string
      default: ""
    - name: CURRENT_WEIGHT
      type: string
      default: ""
    - name: NEXT_WEIGHT
      type: string
      default: ""
    - name: GATEWAY_NAME
      type: string
      default: ""
  steps:
    - name: canary-deploy
      image: quay.io/openshift/origin-cli:4.6
      workingDir: $(workspaces.istio-manifest-dir.path)
      script: |
        #!/usr/bin/env bash

        cat <<EOF >/tmp/patch.yaml
        apiVersion: networking.istio.io/v1alpha3
        kind: VirtualService
        metadata:
          name: $(params.VIRTUAL_SERVICE_NAME)
        spec:
          hosts:
            - "*"
          gateways:
            - $(params.GATEWAY_NAME)
          http:
            - route:
                - destination:
                    host: $(params.APP_NAME)
                    subset: v1
                  weight: $(params.CURRENT_WEIGHT)
                - destination:
                    host: $(params.APP_NAME)
                    subset: v2
                  weight: $(params.NEXT_WEIGHT)
        EOF

        kubectl apply -f /tmp/patch.yaml
